sudo: required
services:
  - docker

before_install:
  - docker build -t pouya/travisbeanstalk:0.0.1 -f Dockerfile.dev .

script: 
  - docker run pouya/travisbeanstalk:0.0.1 npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "TravisBeanstalk"
  env: "Travisbeanstalk-env"
  bucket_name: "elasticbeanstalk-us-west-2-771582200379"
  bucket_path: "TravisBeanstalk"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SCRET_KEY"
  